# Generated by Django 4.1.1 on 2023-06-12 08:22

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=300)),
                ('snippet', models.TextField()),
                ('header_img', models.ImageField(upload_to='header_imgs/')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField()),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
